apiVersion: v1
kind: Service
metadata:
  name: svc-audio-transcriber-clusterip
spec:
  type: ClusterIP
  ports:
    - port: 80           # Internal port used by other services in the cluster
      targetPort: 80      # Port that the container listens on
  selector:
    app: audio-transcriber
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: svce-audio-transcriber-service
# spec:
#   type: NodePort
#   ports:
#     - port: 80           # Internal port in the cluster
#       targetPort: 80      # Port that the container listens on
#       nodePort: 5000      # Port exposed on each node
#   selector:
#     app: audio-transcriber